server:
  port: 9050

# SpringSecurity 의존성이 존재해서 서버를 띄우면 맨처음에 로그인 창이 뜰 것것이다.
# 이 때 id는 admin password는 console 에서 확인할 수 있는데 이 때 해당 부분을 매번 기억하기 어려우니
# applicoation.yml 에서 설정을 해주도록 한다. ( application.yml에는 사용자를 한명만 추가할 수 있다.)
# 소스코드로 관리자를 추가하게되면 application.yml에 설정하 유저아이디는 로그인할 수 없게 됨
spring:
  security:
    user:
      name: user1
      password: 1111
      roles: USER

